# Generated by Django 4.1.9 on 2023-06-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_customuser_date_of_birth_customuser_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
