# Generated by Django 4.1.9 on 2023-07-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="action",
            options={"ordering": ["-created"]},
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["-created"], name="actions_act_created_64f10d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["target_ct", "target_id"], name="actions_act_target__f20513_idx"
            ),
        ),
    ]
